[package]
name = "matmul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "2.3.1"
metal = "0.27.0"
rand = "0.8.5"
rayon = "1.8.0"
separator = "0.4.1"